name: Format C++ code

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install clang-format
      run: sudo apt-get install clang-format
    - name: Run clang-format
      run: |
        clang-format -i src/*.cpp
    - name: Check for unformatted code
      run: git diff --exit-code
