name: CMake auto test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Configure CMake
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    # Build the project
    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    # Run the test executable directly
    - name: Run Tests
      run: ./build/testing
