name: Format C++ code
on: [push]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install clang-format
      run: sudo apt-get install clang-format
    - name: Run clang-format
      run: |
        find . -iname '*.hpp' -o -iname '*.cpp' | xargs clang-format -i --style=Google
    - name: Commit changes if needed
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Apply clang-format changes" || echo "No changes to commit"
    - name: Check for unformatted code
      run: git diff --exit-code
