name: Format C++ code
on: [push]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install clang-format
      run: |
        sudo apt-get update
        sudo apt-get install clang-format -y
        clang-format --version  # Check the version installed for debugging
    - name: Run clang-format
      run: |
        find . -iname '*.hpp' -o -iname '*.cpp' | xargs clang-format -i --style=Google
        git --no-pager diff
    - name: Commit changes if needed
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Apply clang-format changes" || echo "No changes to commit"
    - name: Push changes back to the repository
      run: git push
      env:
        # Use GitHub's token for authentication
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
